function [userDPMode, userObserverMode, userCurrent, userWind, userWave, userCtrl] = simOptions()
%UNTITLED4 Summary of this function goes here
%   Detailed explanation goes here

f = figure('Position', [400, 100, 420, 820], ...
    'Name', 'DP operations', ...
    'MenuBar','none', ...
    'NumberTitle','off', ...
    'WindowStyle','modal');

% DP objective
bg1 = uibuttongroup('Parent', f, ...
    'Position', [0.07 0.73 0.86 0.23], ...
    'Title', 'Select DP objective', ...
    'FontSize', 12, ...
    'FontWeight', 'bold');
obj1 = uicontrol(bg1, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Station Keeping', ...
    'Position',[12 120 300 24]);
obj2 = uicontrol(bg1, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Single Setpoint Path Following', ...
    'Position',[12 85 300 24]);
obj3 = uicontrol(bg1, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Multi Setpoint Path Following', ...
    'Position',[12 50 300 24]);
obj4 = uicontrol(bg1, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Without ref. model', ...
    'Position',[12 15 300 24]);

% Observer selection
bg2 = uibuttongroup('Parent', f, ...
    'Position', [0.07 0.56 0.86 0.15], ...
    'Title', 'Select observer', ...
    'FontSize', 12, ...
    'FontWeight', 'bold');
obs1 = uicontrol(bg2, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','No observer', ...
    'Position',[12 65 300 24]);
obs2 = uicontrol(bg2, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Nonlinear observer', ...
    'Position',[12 38 300 24]);
obs3 = uicontrol(bg2, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Kalman filter', ...
    'Position',[12 11 300 24]);

% Current loads
bg3 = uibuttongroup('Parent', f, ...
    'Position', [0.07 0.39 0.86 0.15], ...
    'Title', 'Select current loads', ...
    'FontSize', 12, ...
    'FontWeight', 'bold');
curr1 = uicontrol(bg3, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Zero current', ...
    'Position',[12 65 300 24]);
curr2 = uicontrol(bg3, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Const direction', ...
    'Position',[12 38 300 24]);
curr3 = uicontrol(bg3, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Var. direction', ...
    'Position',[12 11 300 24]);

% Wind loads
bg4 = uibuttongroup('Parent', f, ...
    'Position', [0.07 0.22 0.86 0.15], ...
    'Title', 'Select wind loads', ...
    'FontSize', 12, ...
    'FontWeight', 'bold');
wind1 = uicontrol(bg4, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','No wind', ...
    'Position',[12 65 300 24]);
wind2 = uicontrol(bg4, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Const direction', ...
    'Position',[12 38 300 24]);
wind3 = uicontrol(bg4, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Var. direction', ...
    'Position',[12 11 300 24]);

% Wave loads
bg5 = uibuttongroup('Parent', f, ...
    'Position', [0.07 0.12 0.86 0.08], ...
    'Title', 'Select wave loads', ...
    'FontSize', 12, ...
    'FontWeight', 'bold');
wave1 = uicontrol(bg5, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','No waves', ...
    'Position',[12 18 140 24]);
wave2 = uicontrol(bg5, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Waves', ...
    'Position',[160 18 140 24]);

% Controller on/off
bg6 = uibuttongroup('Parent', f, ...
    'Position', [0.07 0.02 0.86 0.08], ...
    'Title', 'Controller', ...
    'FontSize', 12, ...
    'FontWeight', 'bold');
ctrl1 = uicontrol(bg6, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','On', ...
    'Position',[12 18 140 24]);
ctrl2 = uicontrol(bg6, ...
    'Style','radiobutton', ...
    'FontSize',11, ...
    'String','Off', ...
    'Position',[160 18 140 24]);

% OK button centered at the bottom
uicontrol('Style','pushbutton', 'String','OK', 'FontSize',12, ...
    'Position',[160 10 100 35], ...
    'Callback', @(src, evt) uiresume(f));

uiwait(f);

% Set defaults if figure was closed
if ~ishandle(bg1) || ~ishandle(bg2) || ~ishandle(bg3) || ~ishandle(bg4) || ~ishandle(bg5) || ~ishandle(bg6)
    userDPMode = 1;
    userObserverMode = 1;
    userCurrent = 1;
    userWind = 1;
    userWave = 1;
    userCtrl = 1;
    try delete(f); end
    return
end

% Determine DP objective
sel1 = bg1.SelectedObject;
if isequal(sel1, obj1)
    userDPMode = 1;
elseif isequal(sel1, obj2)
    userDPMode = 2;
elseif isequal(sel1, obj3)
    userDPMode = 3;
elseif isequal(sel1, obj4)
    userDPMode = 4;
else
    userDPMode = 1;
end

% Determine observer mode
sel2 = bg2.SelectedObject;
if isequal(sel2, obs1)
    userObserverMode = 1;
elseif isequal(sel2, obs2)
    userObserverMode = 2;
elseif isequal(sel2, obs3)
    userObserverMode = 3;
else
    userObserverMode = 1;
end

% Determine current loads
sel3 = bg3.SelectedObject;
if isequal(sel3, curr1)
    userCurrent = 1;
elseif isequal(sel3, curr2)
    userCurrent = 2;
elseif isequal(sel3, curr3)
    userCurrent = 3;
else
    userCurrent = 1;
end

% Determine wind loads
sel4 = bg4.SelectedObject;
if isequal(sel4, wind1)
    userWind = 1;
elseif isequal(sel4, wind2)
    userWind = 2;
elseif isequal(sel4, wind3)
    userWind = 3;
else
    userWind = 1;
end

% Determine wave loads
sel5 = bg5.SelectedObject;
if isequal(sel5, wave1)
    userWave = 1;
elseif isequal(sel5, wave2)
    userWave = 2;
else
    userWave = 1;
end

% Determine controller on/off
sel6 = bg6.SelectedObject;
if isequal(sel6, ctrl1)
    userCtrl = 1;
elseif isequal(sel6, ctrl2)
    userCtrl = 2;
else
    userCtrl = 1;
end

if ishandle(f), delete(f); end
end